const quoteContainer = document.getElementById("quote");
const generateButton = document.getElementById("generate");

// Sample quote data
const quotes = [
    "The only way to do great work is to love what you do.", 
    "Your time is limited, so don't waste it living someone else's life.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Don’t ggwatch the clock; do what it does. Keep going.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Believe you can and you're halfway there.",
    "It always seems impossible until it's done.",
    "Success doesn’t come to you, you go to it.",
    "Push yourself, because no one else is going to do it for you.",
    "The expert in anything was once a beginner.",
    "Don’t stop until you’re proud.",
    "Learning is a treasure that will follow its owner everywhere.",
    "Dream big and dare to fail.",
    "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Strive for progress, not perfection.",
    "The beautiful thing about learning is that no one can take it away from you.",
    "Start where you are. Use what you have. Do what you can.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Education is not the learning of facts, but the training of the mind to think.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Opportunities don't happen, you create them.",
    "Study hard, for the well is deep, and our brains are shallow.",
    "Education breeds confidence. Confidence breeds hope. Hope breeds peace.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Be a student as long as you still have something to learn, and this will mean all your life.",
    "The roots of education are bitter, but the fruit is sweet.",
    "Knowledge will bring you the opportunity to make a difference.",
    "A river cuts through rock, not because of its power, but because of its persistence.",
    "If people knew how hard I worked to gain my mastery, it wouldn't seem so wonderful at all.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Develop a passion for learning. If you do, you will never cease to grow.",
    "Small progress is still progress.",
    "Education is the most powerful weapon which you can use to change the world.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "A well-educated mind will always have more questions than answers.",
    "The journey of a thousand miles begins with one step.",
    "Do something today that your future self will thank you for.",
    "If you think education is expensive, try ignorance.",
    "A mind is like a parachute. It doesn’t work if it is not open.",
    "Never give up, for that is just the place and time that the tide will turn.",
    "Your life does not get better by chance, it gets better by change.",
    "You don’t drown by falling in the water; you drown by staying there.",
    "Be stronger than your excuses.",
    "Success usually comes to those who are too busy to be looking for it.",
    "You are never too old to set another goal or to dream a new dream.",
    "Don’t let what you cannot do interfere with what you can do.",
    "The future starts today, not tomorrow.",
    "A dream does not become reality through magic; it takes sweat, determination, and hard work.",
    "Knowledge is power.",
    "Learning never exhausts the mind.",
    "The more I read, the more I acquire, the more certain I am that I know nothing.",
    "Today a reader, tomorrow a leader.",
    "It’s not about perfect. It’s about effort.",
    "Your education is a dress rehearsal for a life that is yours to lead.",
    "Learning is not attained by chance; it must be sought for with ardor and attended to with diligence.",
    "Discipline is the bridge between goals and accomplishment.",
    "The only place where success comes before work is in the dictionary.",
    "Education is the foundation upon which we build our future.",
    "Motivation gets you going, but discipline keeps you growing.",
    "Your mountain may be harder to climb, but oh, the view is worth it.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "In learning you will teach, and in teaching you will learn.",
    "The secret of success is to do the common thing uncommonly well.",
    "Don't let your victories go to your head, or your failures go to your heart.",
    "Learning is the eye of the mind.",
    "Your passion is waiting for your courage to catch up.",
    "Don't wait. The time will never be just right."
];

generateButton.addEventListener('click', () => {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  quoteContainer.textContent = quotes[randomIndex];
});
